vim9script

# use xdg standard path for config files
set rtp+=~/.config/vim

source ~/.config/vim/plugins.vim

colorscheme slate
# colorscheme koehler
# colorscheme desert
# colorscheme evening
# colorscheme habamax
# colorscheme pablo
# colorscheme retrobox
# colorscheme zaibatsu

# usability settings
set nocompatible
set termguicolors
set showmatch
set incsearch
set ttyfast
set ignorecase
set smartcase
set number
set relativenumber
set cursorline
set title
set autoread
set hidden
set wildmenu
set wildoptions=pum
set t_Co=256
set updatetime=300
set complete+=kspell
set signcolumn=number
set shortmess+=c	# make less noise
set scrolloff=10
set spelllang=en_us
set completeopt+=popup
set omnifunc=g:LspOmniFunc
# set completeopt=menu,popup,noinsert,noselect

# formatting settings
set expandtab
set autoindent
set smartindent
set nowrap
set linebreak
set textwidth=98
set formatoptions+=tjn
set shiftwidth=2
set softtabstop=2

# turn off backup and swap, enable persistent undo
set nobackup
set nowritebackup
set noswapfile
set undofile
set undolevels=10000

# encoding settings
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix

source ~/.config/vim/keymaps.vim
