vim9script

# use xdg standard path for config files
set rtp+=~/.config/vim

source ~/.config/vim/plugins.vim

# def g:GitBranch(): string
#   var branch = system('git branch --show-current 2>/dev/null | tr -d "\n"')
#   return strlen(branch) > 0 ? ' [' .. branch .. ']' : ''
# enddef

colorscheme slate
# colorscheme koehler
# colorscheme desert
# colorscheme evening
# colorscheme habamax
# colorscheme pablo
# colorscheme retrobox
# colorscheme zaibatsu

# usability settings
set nocompatible
set termguicolors
set showmatch
set incsearch
set ttyfast
set ignorecase
set smartcase
set number
set relativenumber
set cursorline
set title
set autoread
set hidden
set wildmenu
set wildoptions=pum
set t_Co=256
set updatetime=300
set complete+=kspell
set signcolumn=number
set shortmess+=c	                               # make less noise
set scrolloff=10
set spelllang=en_us
set completeopt+=popup
set omnifunc=g:LspOmniFunc
set laststatus=2
set statusline=%-F%-M\ %-y%=0x%B\ %p%%
# set statusline=%-F%-M\ %-y%{g:GitBranch()}%=0x%B\ %p%% # creates artifacts on screen

# formatting settings
set expandtab
set autoindent
set smartindent
set nowrap
set linebreak
set textwidth=98
set formatoptions+=tjn
set shiftwidth=2
set softtabstop=2

# turn off backup and swap, enable persistent undo
set nobackup
set nowritebackup
set noswapfile
set undofile
set undolevels=10000

# encoding settings
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix

source ~/.config/vim/keymaps.vim

# make lsp signs nicer
highlight LspDiagSignErrorText ctermbg=NONE guibg=NONE ctermfg=red guifg=red
highlight LspDiagSignHintText ctermbg=NONE guibg=NONE ctermfg=yellow guifg=yellow
highlight LspDiagSignWarningText ctermbg=NONE guibg=NONE ctermfg=lightblue guifg=lightblue
highlight LspDiagSignInfoText ctermbg=NONE guibg=NONE ctermfg=green guifg=green
