vim9script

# curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs \
#    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

syntax on
colorscheme slate
# colorscheme habamax
# colorscheme pablo
# colorscheme retrobox
# colorscheme wildcharm

set rtp+=~/.config/vim
set number
set cursorline

call plug#begin('~/.config/vim/plugged')
call plug#end()
