#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
libera_pwd = "6311F7036D63DC9A62926438A4A94AF63A6CAE42FA252D4592E82E96D1FE3F845A517EFF00EE45F5B9A09ED0D26B947228F7D4A169"
