bt-enable-lpd=true
bt-seed-unverified=true
check-integrity=true
continue=true
daemon=false
dir=/home/f1sty/downloads/torrents
disk-cache=16M
enable-dht6=true
enable-mmap=true
file-allocation=none
follow-metalink=mem
follow-torrent=mem
input-file=/home/f1sty/.config/aria2/files
log-level=warn
lowest-speed-limit=0
max-concurrent-downloads=10
max-connection-per-server=8
max-download-limit=0
max-overall-download-limit=0
max-overall-upload-limit=512K
max-upload-limit=128K
min-split-size=10M
optimize-concurrent-downloads=true
quiet=false
save-session=/home/f1sty/.config/aria2/files
save-session-interval=0
seed-time=0
show-console-readout=true
split=10
