set  -g base-index      1
setw -g pane-base-index 1
set  -g default-shell "/bin/bash"
set -g status-keys vi
set -g mode-keys   vi
set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       0
set  -g history-limit     100000
set -g prefix `
set -g set-clipboard off
set -g renumber-windows on
set -g set-titles on
set -s copy-command 'wl-copy'
set -g status-justify absolute-centre

BG="#202020",
FG="#FFDAB9",
LEFT=""
RIGHT=""
RIGHT_CURRENT=""
LEFT_CURRENT=""

set -g status-left "\
#[bg=#505050,fg=#ffeb99] #S \
#[bg=default,fg=#505050]${LEFT}"
set -g status-right "\
#[bg=default,fg=#505050]${RIGHT}\
#[bg=#505050,fg=#c0e9ff] #h "
set -g status-interval 5
set -g status-style bg=${BG},fg=${FG}
set -g window-status-format "#I:#W"
set -g window-status-current-format "\
#[fg=#303030,bg=default]${LEFT_CURRENT}\
#[fg=default,bg=#303030]#I:\
#[fg=#ff9da4]#W\
#[fg=#303030,bg=default]${RIGHT_CURRENT}"

set -g default-terminal "tmux-256color"
set -g -a terminal-overrides ",st*:Tc:Ss@,*:RGB"
set -s focus-events on
set -s extended-keys on
set -s escape-time 0

unbind c-b
unbind h
unbind j
unbind k
unbind l
unbind %
unbind '"'
unbind c-n
bind ` send-prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind y display-popup -w 80% -h 80% -E "rmpc"
bind -r C-h resize-pane -L 1
bind -r C-j resize-pane -D 1
bind -r C-k resize-pane -U 1
bind -r C-l resize-pane -R 1
bind -r m resize-pane -Z
bind X confirm kill-window
bind K confirm kill-server
bind r source-file /home/f1sty/.config/tmux/tmux.conf \; display "config reloaded"
bind c-b last-window
bind b set-option status
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
