[[ $- != *i* ]] && return

export GPG_TTY="$(tty)"

HISTCONTROL="erasedups" # don't put duplicate lines or lines starting with space in the history.
HISTSIZE="-1"           # unlimited
HISTFILESIZE="-1"       # do not truncate history file

shopt -so vi            # use a vi-style line editing interface
shopt -so noclobber     # disallow existing regular files to be overwritten by redirection of output
shopt -so pipefail      # return any non-zero return code if there was one
shopt -s checkwinsize   # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
shopt -s histappend     # append to the history file, don't overwrite it
shopt -s autocd         # if command is a dir name - `cd` into it
shopt -s expand_aliases
shopt -s cdspell
shopt -s dirspell
shopt -s globstar

complete -cf doas

source /usr/share/bash-completion/completions/fzf
source /usr/share/fzf/key-bindings.bash

eval "$(starship init bash)"
