# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$username\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""

[username]
show_always = true
format = '[$user]($style)@'

[localip]
disabled = false
ssh_only = false
format = '[$localipv4](bold blue):'

[directory]
style = 'bold green'

[character]
success_symbol = '[\$](bold blue)'
error_symbol = '[\$](bold red)'

[cmd_duration]
disabled = true
